import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-4">
          <nav className="glass rounded-xl p-2 mb-4 flex gap-3 text-sm">
            <Link className="btn-glass btn-sm" href="/">Посты</Link>
            {/* Генерация перенесена на главную как фича создания постов */}
            <Link className="btn-glass btn-sm" href="/calendar">Календарь</Link>
            <Link className="btn-glass btn-sm" href="/table">Таблица</Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
