import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isHydratingScript = `
    window.__aion_loading = 0;
    document.addEventListener('aion:load:start', ()=>{ window.__aion_loading++; toggle(); });
    document.addEventListener('aion:load:end', ()=>{ window.__aion_loading = Math.max(0, window.__aion_loading-1); toggle(); });
    function toggle(){
      const el = document.getElementById('global-spinner');
      if (!el) return;
      el.style.display = (window.__aion_loading>0) ? 'flex' : 'none';
    }
  `;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="global-spinner" style={{display:'none'}} className="fixed inset-0 z-[1000] items-center justify-center" >
          <div className="absolute inset-0 bg-black/40" />
          <div className="relative z-[1001] spinner" />
        </div>
        <div className="p-4">
          <nav className="glass rounded-xl p-2 mb-4 flex gap-3 text-sm">
            <Link className="btn-glass btn-sm" href="/">Посты</Link>
            {/* Генерация перенесена на главную как фича создания постов */}
            <Link className="btn-glass btn-sm" href="/calendar">Календарь</Link>
            <Link className="btn-glass btn-sm" href="/table">Таблица</Link>
          </nav>
          {children}
        </div>
        <script dangerouslySetInnerHTML={{ __html: isHydratingScript }} />
      </body>
    </html>
  );
}
